### ISSUE TITLE
The engine does not verify the header of the grammar files.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ridencww/goldengine#13]
According to GOLD Parser's documentation, grammar files have a header at the beginning (cgt class reads it).

However, the Parser class does not check that header. This could lead to more errors.

**Comment by ridencww** [comment]
It is true that the engine doesn't validate that the header contains the Unicode string "GOLD Parser Tables/1.0", but it does advance beyond the header in order to process the structured data, which raises errors if invalid data is encountered. A check would provide a quick test to see if it is a CGT file being submitted for parsing, but the engine depends to a great degree on having the GOLD Builder produce a correct CGT/EGT file for consumption.  A separate class to validate the CGT/EGT file could be written, but I can't remember ever having the GOLD Builder generate an incorrect file that couldn't be handled by the engine.  Any errors were due to my implementation of the engine.

Thank you for raising this issue and consider improving my validation of the CGT file if I return to extend engine in the future.

**Comment by teo-tsirpanis** [comment]
I don't think that a special class is needed. Just return "False" if the header is different.

**Comment by ridencww** [comment]
I am working on a reported defect and will see if I can add the header check at the same time.
